name: Sync Changes in Template
on:
  # cronjob trigger
  # schedule:
  # - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: template-sync
        id: template_sync
        continue-on-error: true
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: cormoran/zmk-module-template-with-custom-studio-rpc
          upstream_branch: main # defaults to main
          # pr_labels: <label1>,<label2>[,...] # defaults to template_sync
      - name: template-sync-with-pat-as-fallback
        # If the above step fails due to permission issues (e.g. changes in .github/workflow/*),
        # try again with a personal access token.
        # The token requires `repo` and `workflow` scopes.
        if: steps.template_sync.outcome == 'failure'
        uses: AndreasAugustin/actions-template-sync@v2
        with:
            source_repo_path: cormoran/zmk-module-template-with-custom-studio-rpc
            upstream_branch: main # defaults to main
            source_gh_token: ${{ secrets.GITHUB_TOKEN }}
            # pr_labels: <label1>,<label2>[,...] # defaults to template
